{
 "title": "Workplaces status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10m,30m,1h,6h,8h,10h,12h,1d,5d,7d"
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(up{host_type=\"workplace\"}, group)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{host_type=\"workplace\",group=\"$group\"}, instance)"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "query_result(node_disk_writes_completed_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"} or windows_logical_disk_writes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Graph View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) ((1 - rate(windows_cpu_time_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",mode=\"idle\"}[1m])) * on (instance, core) avg_over_time(windows_cpu_core_frequency_mhz[1m]))) * 1000000",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by (instance) ((1 - sum by (instance, cpu) (rate(node_cpu_seconds_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",mode=\"idle\"}[1m]))) * on (instance, cpu) avg_over_time(node_cpu_scaling_frequency_hertz[1m])) \nor\n(avg by (instance) (1 - sum by (instance, cpu) (rate(node_cpu_seconds_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",mode=\"idle\"}[1m])))) * on(instance) group_left(node) (label_copy((label_copy((system_vmid{host=~\"$host\"} / on(host,nodename) system_vmid), \"host\",\"instance\")),\"nodename\",\"node\")) * on (instance) group_right (node) count by (instance) (node_cpu_seconds_total{mode=\"idle\"}) * on (node) group_right(instance) (label_copy((avg by (instance) (node_cpu_scaling_frequency_hertz)), \"instance\", \"node\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"} - windows_os_physical_memory_free_bytes)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\"$disk\"} - windows_logical_disk_free_bytes",
     "legendFormat": "{{instance}} - disk {{volume}}"
    },
    {
     "expr": "node_filesystem_size_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"/dev/${disk}.*\"} - node_filesystem_free_bytes",
     "legendFormat": "{{instance}} - disk {{device}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_reads_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{volume}}"
    },
    {
     "expr": "rate(node_disk_reads_completed_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_writes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{volume}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{volume}}"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{volume}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"$disk\"}[5m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"}[5m]) * 8",
     "legendFormat": "{{instance}} - {{nic}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"ens.*|eno.*|eth.*|enp.*\"}[5m]) * 8",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_net_bytes_sent_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"}[5m]) * 8",
     "legendFormat": "{{instance}} - {{nic}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"ens.*|eno.*|eth.*|enp.*\"}[5m]) * 8",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Table View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Windows",
     "type": "table",
     "description": "CPU = sum by (cores) (core usage * core frequency)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "avg_over_time(sum by (instance) ((1 - rate(windows_cpu_time_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",mode=\"idle\"}[1m])) * on (instance, core) avg_over_time(windows_cpu_core_frequency_mhz[1m]))[$interval]) * 1000000"
      },
      {
       "expr": "max_over_time(sum by (instance) ((1 - rate(windows_cpu_time_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",mode=\"idle\"}[1m])) * on (instance, core) avg_over_time(windows_cpu_core_frequency_mhz[1m]))[$interval]) * 1000000"
      },
      {
       "expr": "max_over_time((windows_cs_physical_memory_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"} - windows_os_physical_memory_free_bytes)[$interval])"
      },
      {
       "expr": "avg_over_time((windows_cs_physical_memory_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"} - windows_os_physical_memory_free_bytes)[$interval])"
      },
      {
       "expr": "sum by (instance) (windows_logical_disk_size_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"} - windows_logical_disk_free_bytes)"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(windows_logical_disk_write_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(windows_logical_disk_read_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(windows_logical_disk_write_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(windows_logical_disk_read_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(windows_logical_disk_reads_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(windows_logical_disk_reads_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(windows_logical_disk_writes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(windows_logical_disk_writes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",volume=~\".*:\"}[5m]))[$interval])"
      }
     ]
    },
    {
     "title": "Linux",
     "type": "table",
     "description": "CPU = sum by (cores) (core usage * core frequency)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "avg_over_time(sum by (instance) ((1 - sum by (instance, cpu) (rate(node_cpu_seconds_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",mode=\"idle\"}[1m]))) * on (instance, cpu) avg_over_time(node_cpu_scaling_frequency_hertz[1m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) ((1 - sum by (instance, cpu) (rate(node_cpu_seconds_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",mode=\"idle\"}[1m]))) * on (instance, cpu) avg_over_time(node_cpu_scaling_frequency_hertz[1m]))[$interval])"
      },
      {
       "expr": "max_over_time((node_memory_MemTotal_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)[$interval])"
      },
      {
       "expr": "avg_over_time((node_memory_MemTotal_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)[$interval])"
      },
      {
       "expr": "sum by (instance) (node_filesystem_size_bytes{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"/dev/sd.*|/dev/nvme.*|/dev/vd.*\"} - node_filesystem_free_bytes)"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(node_disk_written_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(node_disk_read_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(node_disk_written_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(node_disk_read_bytes_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(node_disk_reads_completed_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(node_disk_reads_completed_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      },
      {
       "expr": "avg_over_time(sum by (instance) (rate(node_disk_writes_completed_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      },
      {
       "expr": "max_over_time(sum by (instance) (rate(node_disk_writes_completed_total{host_type=\"workplace\",group=~\"$group\",instance=~\"$host\",device=~\"sd.*|nvme.*|vd.*\"}[5m]))[$interval])"
      }
     ]
    }
   ]
  }
 ]
}