{
 "title": "Devops-Service - Windows",
 "tags": [
  "nodes",
  "windows",
  "devops-service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(windows_os_info{host_type=\"devops-service\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(windows_os_info{host_type=\"devops-service\",cluster=\"$cluster\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "sd.*|nvme.*|vd.*" },
   { "name": "networkinterfaces", "query": "eno.*|eth.*|enp.*|ens.*" }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg by (instance) (irate(windows_cpu_time_total{cluster=\"$cluster\",host_type=\"devops-service\",instance=\"$node\",mode=\"idle\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{cluster=\"$cluster\",host_type=\"devops-service\",instance=\"$node\"} - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes * 100"
    }
   ]
  },
  {
   "title": "C: Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{cluster=\"$cluster\",host_type=\"devops-service\",instance=\"$node\",volume=~\"C:\"} - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{cluster=\"$cluster\",host_type=\"devops-service\",instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{cluster=\"$cluster\",host_type=\"devops-service\",instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (windows_cs_physical_memory_bytes{cluster=\"$cluster\",host_type=\"devops-service\",instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "C: Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (windows_logical_disk_size_bytes{cluster=\"$cluster\",host_type=\"devops-service\",instance=\"$node\",volume=~\"C:\"})"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(windows_cpu_time_total{cluster=\"$cluster\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$node\"} - windows_os_physical_memory_free_bytes{instance=~\"$node\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"$node\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{instance=~\"$node\"}[5m]) * 8 > 0",
     "legendFormat": "recv {{nic}}"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{instance=~\"$node\"}[5m]) * 8 > 0",
     "legendFormat": "trans {{nic}} "
    }
   ]
  },
  {
   "title": "Volume Space Used Basic",
   "type": "graph",
   "description": "Disk space used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{instance=~\"$node\",volume=~\".*:\"} / windows_logical_disk_size_bytes)*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_split_ios_total{instance=~\"$node\", volume =~\".*:\"}[30s])",
     "legendFormat": "i/o {{volume}}"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "- irate(windows_logical_disk_read_bytes_total{instance=~\"$node\", volume =~\".*:\"}[5m])",
     "legendFormat": "{{volume}} - Successfully read bytes"
    },
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$node\", volume =~\".*:\"}[5m])",
     "legendFormat": "{{volume}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "irate(windows_logical_disk_read_write_latency_seconds_total{instance=\"$node\",volume=~\".*:\"}[5m])",
     "legendFormat": "{{volume}} - Time spent doing I/Os"
    }
   ]
  },
  { "title": "Memory Meminfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory Commited",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_memory_committed_bytes {instance=\"$node\"}",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "windows_memory_commit_limit{instance=\"$node\"}",
     "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
    }
   ]
  },
  {
   "title": "Memory page faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "faults" }
   ],
   "targets": [
    {
     "expr": "irate(windows_memory_page_faults_total{instance=\"$node\"}[5m])",
     "legendFormat": "Memory page faults"
    }
   ]
  },
  {
   "title": "Memory transition faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "faults" }
   ],
   "targets": [
    {
     "expr": "irate(windows_memory_transition_faults_total{instance=\"$node\"}[5m])",
     "legendFormat": "Memory transition faults"
    }
   ]
  },
  {
   "title": "Memory cache faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "faults" }
   ],
   "targets": [
    {
     "expr": "irate(windows_memory_cache_faults_total{instance=\"$node\"}[5m])",
     "legendFormat": "Memory cache faults"
    }
   ]
  },
  { "title": "System Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Clock tick interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sum(windows_cpu_clock_interrupts_total{instance=\"$node\"})[5m])"
    }
   ]
  },
  {
   "title": "Hardware interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sum(windows_cpu_interrupts_total{instance=\"$node\"})[5m])"
    }
   ]
  },
  {
   "title": "System threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{instance=~\"$node\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System context switches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_system_context_switches_total{instance=~\"$node\"}[1m])"
    }
   ]
  },
  {
   "title": "System exception dispatches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_system_exception_dispatches_total{instance=~\"$node\"}[5m])"
    }
   ]
  },
  {
   "title": "System calls total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_system_system_calls_total{instance=~\"$node\"}[1m])"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$node\"}",
     "legendFormat": "Maximum open file descriptors"
    },
    {
     "expr": "process_open_fds{instance=\"$node\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "CPU time spent in user and system contexts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$node\"}[5m])",
     "legendFormat": "Time spent"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Network Packets Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_sent_total{instance=~\"$node\", nic!~\"isatap.+|.*ISATAP.*\"}[5m])",
     "legendFormat": "{{nic}} - Transmit"
    },
    {
     "expr": "irate(windows_net_packets_received_total{instance=~\"$node\", nic!~\"isatap.+|.*ISATAP.*\"}[5m])",
     "legendFormat": "{{nic}} - Receive"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_errors_total{instance=~\"$node\", nic!~\"isatap.+|.*ISATAP.*\"}[5m])",
     "legendFormat": "{{nic}} - Transmit errors"
    },
    {
     "expr": "irate(windows_net_packets_received_errors_total{instance=~\"$node\", nic!~\"isatap.+|.*ISATAP.*\"}[5m])",
     "legendFormat": "{{nic}} - Receive errors"
    }
   ]
  },
  {
   "title": "Network Traffic Discards",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_discarded_total{instance=~\"$node\", nic!~\"isatap.+|.*ISATAP.*\"}[5m])",
     "legendFormat": "{{nic}} - Transmit discards"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded_total{instance=~\"$node\", nic!~\"isatap.+|.*ISATAP.*\"}[5m])",
     "legendFormat": "{{nic}} - Receive discards "
    }
   ]
  },
  {
   "title": "Network Receive Unknown",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_received_unknown_total{instance=~\"$node\", nic!~\"isatap.+|.*ISATAP.*\"}[5m])",
     "legendFormat": "{{nic}} - Receive unknown"
    }
   ]
  },
  { "title": "Services Basic info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "windows_service_info{instance=\"$node\"}"
    },
    {
     "expr": "(windows_service_start_mode{instance=\"$node\"} == 1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(windows_service_state{instance=\"$node\"} == 1)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "(windows_service_status{instance=\"$node\"} == 1)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Service status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_status{instance=~\"$node\"}) by (status)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{status}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Services by state",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{instance=~\"$node\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Services by start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_start_mode{instance=~\"$node\"}) by (start_mode)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{start_mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Services - CPU Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "CPU Time Privileged",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_cpu_time_total{instance=\"$node\",mode=\"privileged\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "CPU Time User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_cpu_time_total{instance=\"$node\",mode=\"user\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_process_thread_count{instance=\"$node\"}",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  { "title": "Services - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "Private memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_process_private_bytes{instance=\"$node\"}",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_process_working_set{instance=\"$node\"}",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "Page bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_process_page_file_bytes{instance=\"$node\"}",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 186 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_page_faults_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "Pool bytes - Paged",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_process_pool_bytes{instance=\"$node\",pool=\"paged\"}",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "Pool bytes - Nonpaged",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 195 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_process_pool_bytes{instance=\"$node\",pool=\"nonpaged\"}",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  { "title": "Services - IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 } },
  {
   "title": "IO - read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{instance=\"$node\",mode=\"read\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "IOPS - read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 205 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_operations_total{instance=\"$node\",mode=\"read\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "IO - write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{instance=\"$node\",mode=\"write\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "IOPS - write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 214 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_operations_total{instance=\"$node\",mode=\"write\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "IO - other",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{instance=\"$node\",mode=\"other\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  {
   "title": "IOPS - other",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_operations_total{instance=\"$node\",mode=\"other\"}[5m])",
     "legendFormat": "{{process_id}} - {{process}}"
    }
   ]
  },
  { "title": "Windows Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 } },
  {
   "title": "Collector success",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 233 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_exporter_collector_success{instance=~\"$node\"}) by (collector)",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Collector duration seconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 233 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(windows_exporter_collector_duration_seconds{instance=~\"$node\"}) by (collector)",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Collector timeout",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 243 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_exporter_collector_timeout{instance=~\"$node\"}) by (collector)",
     "legendFormat": "{{collector}}"
    }
   ]
  }
 ]
}