route:
  receiver: slack
  routes:
    - match:
        severity: warning
      group_wait: 45s
      group_interval: 5m
      repeat_interval: 24h
      receiver: slack
      group_by: [cluster, alertgroup, instance]
      continue: true
    - match:
        severity: critical
      group_wait: 45s
      group_interval: 5m
      repeat_interval: 24h
      receiver: slack
      group_by: [cluster, alertgroup, instance]
      continue: true

inhibit_rules:
- source_match:
    alertname: 'ExporterDown'
  target_match:
    alertname: 'LinstorNodeNotOnline'
  equal: ['cluster', 'instance']
- source_match:
    alertname: 'OutOfQuorum'
  target_match:
    alertname: 'OutOfSync'
  equal: ['cluster', 'name']
- source_match:
    alertname: 'OutOfSync'
  target_match:
    alertgroup: 'linstor resource state'
  equal: ['cluster', 'name']
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'instance']
- source_match:
    alertname: 'ExporterDown'
  target_match:
    alertname: 'SiteDown'
  equal: ['cluster', 'instance']
- source_match:
    alertname: 'ExporterDown'
  target_match:
    alertname: 'PortDown'
  equal: ['cluster', 'instance']
- source_match:
    alertname: 'ExporterDown'
  target_match:
    alertname: 'ICMPFail'
  equal: ['cluster', 'instance']

receivers:
  #- name: amixr-it
  #  webhook_configs:
  #    - url: https://
  #      send_resolved: true
  #- name: amixr-prod
  #  webhook_configs:
  #    - url: https://
  #      send_resolved: true
  - name: slack
    slack_configs:
      - api_url: https://
        channel: devops_alerts
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
  #- name: mail-mango
  #  email_configs:
  #    - to: 'service@mango-telecom.ru'
  #      from: 'devops@xxx.ru'
  #       require_tls: false
  #       send_resolved: false
  #       smarthost: mail.xxx.ru:25
  #       hello: 'devops.xxx.ru'
  #       html: '{{ template "email.simple.html" .}}'
  #       headers:
  #         subject: "{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"
  #         cc: 'it@xxx.ru'
  #- name: prometheus-am-executor
  #  webhook_configs:
  #    - url: http://
  #      send_resolved: false

#templates:
#- '/config/templates/mytemplates.tmpl'