{
 "title": "AlertManager",
 "tags": [ "alertmanager" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "severity=\"warning\",cluster=~\"$cluster\"",
     "filters": "severity=\"warning\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Criticals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "severity=\"critical\",cluster=~\"$cluster\"",
     "filters": "severity=\"critical\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\"",
     "labelSelector": "severity,cluster,summary,description",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}